name: movie_teca
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  auto_route: ^7.8.4
  retrofit: ^4.0.3
  dio: ^5.3.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  cached_network_image: ^3.3.0
  ionicons: ^0.2.2
  json_annotation: ^4.8.0
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.0.4
  build_runner: ^2.4.6
  json_serializable: ^6.0.0
  flutter_lints: ^2.0.0
  mockito: ^5.0.0

flutter:
  uses-material-design: true